//number id of the option taken in the dialogue, starts at 0
var OPTION=0

//id of the dialogue
var DIAGID=464

//x y z coords to place block in
var COORDS=[2480,171,1243]

//block to spawn
var BLOCK="minecraft:redstone_block"


//timer (in seconds) to return that block to air, set to -1 to not do so

var TIME=4

//place block in location after closing a dialogue

/**
 * @param {NpcEvent.TimerEvent} event
 */

function timer(event)
{
    if(event.id==1)
    {
        var pos =event.API.getIPos(COORDS[0],COORDS[1],COORDS[2])
        event.npc.getWorld().setBlock(pos, "minecraft:air")
    }
}

/**
 * @param {DialogEvent.OptionEvent} event
 */

 function dialogOption(event){
    if(event.dialog.getId()==DIAGID && event.option.getSlot()==OPTION)
    {
        var pos =event.API.getIPos(COORDS[0],COORDS[1],COORDS[2])
        event.npc.getWorld().setBlock(pos, BLOCK)
        if(TIME!=-1)
        {
            event.npc.getTimers().stop(1)
            event.npc.getTimers().start(1, TIME*20, false);
        }
    }
    }

    /*ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD 
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD

    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD*/