//number id of the option taken in the dialogue, starts at 0
var OPTION=0

//id of the dialogue
var DIAGID=464

//x y z coords to place block in
var COORDS=[2480,171,1243]

//block to spawn
var BLOCK="minecraft:redstone_block"


//timer (in seconds) to return that block to air, set to -1 to not do so

var TIME=4

//place block in location after closing a dialogue

/**
 * @param {NpcEvent.TimerEvent} event
 */

function timer(event)
{
    if(event.id==1)
    {
        var command='setblock '+COORDS[0].toString()+' '+COORDS[1].toString()+' '+COORDS[2].toString()+' '+"minecraft:air"
        event.npc.executeCommand(command)

    }
}

/**
 * @param {DialogEvent.OptionEvent} event
 */

 function dialogOption(event){
    if(event.dialog.getId()==DIAGID && event.option.getSlot()==OPTION)
    {
        var command='setblock '+COORDS[0].toString()+' '+COORDS[1].toString()+' '+COORDS[2].toString()+' '+BLOCK
        command="minecraft:setblock 2480 171 1243 minecraft:redstone_block"
        event.npc.say(command)
        event.npc.executeCommand(command)

        if(TIME!=-1)
        {
            event.npc.getTimers().stop(1)
            event.npc.getTimers().start(1, TIME*20, false);
        }
    }
    }

    /*ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD 
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD

    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD*/