
//number id of the option taken in the dialogue, starts at 0
var OPTION=0

//id of the dialogue
var DIAGID=463

//x y z coords to move to
var COORDS=[2498.0,171.0,1259.0]

//speed at which the npc should move
var SPEED=1
//should npc return to base location after walking?
var RETURNHOME=false


//move to location after closing a dialogue

/**
 * @param {DialogEvent.OptionEvent} event
 */

 function dialogOption(event){
    if(event.dialog.getId()==DIAGID && event.option.getSlot()==OPTION)
    {
        event.npc.ai.setReturnsHome(RETURNHOME)
        event.npc.navigateTo(COORDS[0],COORDS[1],COORDS[2],SPEED)
    }
    }

    /*ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD 
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD

    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD
    ASDADSSDASDAASDASDASDASDASDASDASDASDASDSADASDASD*/